theme: jekyll-theme-slate
title: Welcome to the bloodthirsty side of friendly!
description: high-functioning sociopathic CS adventurer exploring data science and other haberdashery
email: ksngstr@gmail.com
